import Groups from "./../component/Groups";
import Header from "./../component/Header";
import Head from "next/head";
import { groups } from "./../data/fifa";

const Fifa = () => {
  return (
    <div className="bg-red-900 ">
      <Head>
        <title>Next.js-FIFA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Groups groups={groups} />
    </div>
  );
};

export default Fifa;
